resolve the open issue of different interfaces for models
alexhernandezgarcia/ActiveLearningPipeline pull request #16
Opened 2022-10-27 21:12 UTC by nikita-0209

2022-10-29 12:37 UTC, Baobabtou commented on acquisition.py
> +            outputs = self.proxy.model(inputs, input_afs_lens, None)
that could be the same in AcquisitionFunctionUCB, etc... no ? without distinguishing between the proxies to call  the proxy model

2022-11-01 20:27 UTC, alexhernandezgarcia requested changes

2022-11-01 20:27 UTC, alexhernandezgarcia commented on proxy.py
> +        output = self.model(inputs, inputLens, targets)
For variable names, always use convention `input_lens` instead of `inputLens`.

2022-11-01 21:47 UTC, alexhernandezgarcia approved these changes
Good!

2022-11-01 21:47 UTC, merged